#! /bin/sh

export PATH=$PATH:~/bspwmextra

sxhkd &
compton &
albert &
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceCompositionPipeline = On }" &
urxvt &
xautolock -time 10 -locker lock &
wal -i Pictures/GalaxyWallpaper.jpg &
$HOME/.config/polybar/launch.sh &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"
bspc config presel_border_color "$color1"

bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         6
bspc config window_gap           32

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus  true

bspc rule -a Gimp desktop='^8' state=floating follow=off
bspc rule -a Chromium desktop='^2' follow=off
bspc rule -a spotify desktop='^4'
bspc rule -a Spotify desktop='^4'
bspc rule -a Steam desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config pointer_modifier mod4
bspc config pointer_action1 resize

bspc desktop 0x00400004 -n term
bspc desktop 0x00400005 -n web
bspc desktop 0x00400006 -n code
bspc desktop 0x00400007 -n music
bspc desktop 0x00400008 -n game





